config/routes.rb
Rails.application.routes.draw do
  root to: "tasks#index"
  resources :tasks, only: [:index, :new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true
  default_scope { order(time: :desc) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:destroy]

  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end

  def create
    # binding.pry
    @task = Task.new(task_params)

    if @task.save
      redirect_to tasks_url, notice: 'Task successfully created.'
    else
      render :new
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_url, notice: 'Task successfully destroyed.'
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:description, :title, :time)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WorkshopsTodo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,400i,500,500i,700,700i' rel='stylesheet'
          type='text/css'>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/index.html.erb
<div class='main-content'>
  <div class='basic'>
    <div class="card">
      <h1 class="card-header">
        Tasks
      </h1>
      <div class="card-body">
        <% if notice %>
            <div class='alert alert-info'>
            <span style="font-weight: normal">
              <%= notice %>
            </span>
            </div>
        <% end %>

        <div class='btn btn-sm button'>
          <%= link_to 'New Task', new_task_path, :class => 'btn btn-sm btn-outline-success' %>
        </div>
        <% @tasks.each do |task| %>
            <div class='list'>

              <div class="content-left">
                <h5 class="title">
                  <%= task.title %>
                </h5>

                <p class="description">
                  <%= task.description %>
                </p>

                <p class="time">
                  (<b>Deadline:</b> <%= distance_of_time_in_words_to_now(task.time) %>)
                  <%= task.time.strftime('%H:%M:%S %d.%m.%Y') %>
                </p>

              </div>

              <div class="content-right">
                <div class="btn btn-sm">
                  <%= link_to 'Done', task, method: :delete,
                              data: {confirm: 'Sure that you dont have to do this task?'},
                              :class => 'btn btn-sm btn-outline-danger' %>
                </div>
              </div>

            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/tasks/new.html.erb
<div class='main-content'>
  <div class='basic'>
    <div class="card">
      <h1 class="card-header">
        Add New Task
      </h1>

      <div class="card-body">
        <%= form_for(@task, url: tasks_path) do |f| %>

            <% if @task.errors.any? %>
                <div class="alert alert-danger">
                  <% @task.errors.full_messages.each do |message| %>
                    <span style="font-weight: normal">
                      <%= message %>
                    </span>
                  <% end %>
                </div>
            <% end %>
            <div class="btn btn-sm button">
              <%= link_to 'Tasks list', tasks_path, :class => 'btn btn-sm btn-outline-secondary' %>
            </div>


            <div class='row field'>
              <label>
                <span class="field-header">Title</span>
                <%= f.text_field :title %>
              </label>
            </div>

            <div class='row field'>
              <label>
                <span class="field-header">Description</span>
                <%= f.text_area :description %>
              </label>
            </div>

            <div class='row field'>
              <label>
                <span class="field-header">Time</span>
                <%= f.datetime_select :time %>
              </label>
            </div>

            <div>
              <button type="submit" class="btn btn-primary">Add task</button>
            </div>

        <% end %>
      </div>

    </div>
  </div>
</div>